# Creating DataFrame

## Creating a dictionary

In [25]:
import pandas as pd

data = {'Animals':['cow','chicken','rabbit','goats'],
        'Age':[4,1,2,3],
        'Cost':[20000,2000,4000,10000]}
df=pd.DataFrame (data)
df

## From a list of lists

In [27]:
Data = [['cow',4,20000],
        ['chicken',1,2000],
        ['rabbit',2,4000],
        ['goats',3,10000]]
df=pd.DataFrame (data,columns= ['Animals','Age','Cost'])
df

   Animals  Age   Cost
0      cow    4  20000
1  chicken    1   2000
2   rabbit    2   4000
3    goats    3  10000

## From a CSV file

In [28]:
df=pd.read_CVS ('data.cvs')
df

AttributeError: module 'pandas' has no attribute 'read_CVS'

## From a Numpy Array

In [29]:
import numpy as np

In [31]:
arr = np.array ([[1,2,3],[4,5,6]])
df=pd.DataFrame (arr,columns=['A','B','C'])
print(df)

   A  B  C
0  1  2  3
1  4  5  6

## From a dictionary with lists (index)

In [38]:
data = {'Name':['John','Victor','Edwin'],
        'Age':[20,19,17]}
df=pd.DataFrame (data, index=['Row1','row2','Row3'])
df

        Name  Age
Row1    John   20
row2  Victor   19
Row3   Edwin   17